#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# mask the user service to fix pam_systemd.so not working (XDG_* not set, login not working, permissions net set, ...)
#$ROOTCMD systemctl mask user@.service
#$ROOTCMD systemctl --global mask tracker-store.service
# mask the pulseaudio-service, because this keeps crashing "systemd --user" (we start pulseaudio manually in CIP/usr/local/bin/run_always/startup-script)
$ROOTCMD systemctl --global --user mask pulseaudio.service
$ROOTCMD systemctl --global --user mask pulseaudio.socket

exit $error
