#! /bin/bash
# use updated AFS repository

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

#$ROOTCMD add-apt-repository -y ppa:openafs/stable
#$ROOTCMD apt -y update
#$ROOTCMD apt -y upgrade
#$ROOTCMD apt -y install openafs-client openafs-modules-dkms openafs-krb5 krb5-user krb5-config


exit $error
