#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Set LightDM to be standard display manager, necessary for AFS
#echo "/usr/sbin/lightdm" | $ROOTCMD tee /etc/X11/default-display-manager
#$ROOTCMD DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm
#echo set shared/default-x-display-manager lightdm | $ROOTCMD debconf-communicate

# set the necessary debconf values
#$ROOTCMD bash -c 'echo "gdm3 shared/default-x-display-manager select lightdm" | debconf-set-selections'
#$ROOTCMD bash -c 'echo "lightdm shared/default-x-display-manager select lightdm" | debconf-set-selections'
#$ROOTCMD bash -c 'echo "lightdm lightdm/daemon_name string /usr/sbin/lightdm" | debconf-set-selections'

#$ROOTCMD bash -c 'DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm'

#echo "20-lightdm: the display manager is set to /etc/X11/default-display-manager:"
#cat $target/etc/X11/default-display-manager

exit $error
