#!/bin/bash

# Installs needed Julia Packages

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# array of julia versions: juliaVersArr
# main versions (will be suffixed with -stable and -lts): juliaVersStable, juliaVersLTS
# load the list of versions (and juliaVersStable and juliaVersLTS) from the config file
source $FAI/files/archives/APPS/opt/get-julia-versions.conf

# install non-minimal packages for all versions (except stable)
for vers in "${!juliaVersArr[@]}"; do
    if [ "$vers" = "$juliaVersStable" ]; then
        # do that last
    else
        # other versions
        $ROOTCMD $vers $juliapath/julia_init.jl --install-non-min
    fi
done

# install non-minimal packages # LTS
# $ROOTCMD $juliaVersLTS $juliapath/julia_init.jl --install-non-min
# install non-minimal packages for default (stable)
$ROOTCMD julia $juliapath/julia_init.jl --install-non-min

exit $error
