#!/bin/bash

# installiert den Zoom-Client
# Quelle: https://zoom.us/client/latest/zoom_amd64.deb

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

file="zoom_amd64.deb"

# Installationsdatei auf den Klienten uebertragen
cp $FAI/files/$file $target/tmp/

# Installation ausfuehren
$ROOTCMD apt install -y /tmp/$file
#$ROOTCMD dpkg -i /tmp/$file # old

exit $error
