#!/bin/bash

# Configures Julia (withouth packages)
# Packages are loaded in the JULIA class
# Julia must be already distributed into $files/JULIA/opt 
# Suggested versions to install (min):
#   - /opt/julia -> latest LTS
#   - latest stable
#   - some older stable/lts versions (if needed)

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

julialts="julia" # /opt/julia -> /opt/julia-1.6.5-lts
juliastable="julia-1.7.1-stable" # current
# juliastablev160="julia-1.6.0-stable" # add more in APPS/opt/ if needed

# link all versions in /usr/bin/
$ROOTCMD ln -s $juliapath/$julialts/bin/julia /usr/bin/julia
$ROOTCMD ln -s $juliapath/$juliastable/bin/julia /usr/bin/julia-1.7.1
# $ROOTCMD ln -s /$juliapath/$juliastablev160/bin/julia /usr/bin/julia-1.6.0 # add more if needed

# create directory and export path
$ROOTCMD mkdir -p $JULIA_DEPOT_PATH
ainsl    /etc/bash.bashrc "export JULIA_DEPOT_PATH=/usr/share/julia/"

# export path to user specific REPL-history file (otherwise get's shared with all users)
ainsl    /etc/bash.bashrc 'export JULIA_HISTORY=$HOME/.julia/logs/repl_history.jl'

# install minimal packages (IJulia)
$ROOTCMD julia $juliapath/julia_init.jl --install-min
$ROOTCMD julia-1.7.1 $juliapath/julia_init.jl --install-min

# copy IJulia Kernel to $jupyter_kernels
$ROOTCMD chown -R root:smail $JULIA_DEPOT_PATH
#$ROOTCMD chmod -R g+rw $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH/registries/General
#$ROOTCMD mv -i .local/share/jupyter/kernels/julia-* $jupyter_kernels/
$ROOTCMD cp -a .local/share/jupyter/kernels /usr/local/share/jupyter/

# add cronjob for 
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia"
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia/registries/General"


exit $error
