#!/bin/bash

# Configures Julia (withouth packages)
# Packages are loaded in the JULIA class
# Julia must be already distributed into $files/JULIA/opt 
# Suggested versions to install (min):
#   - /opt/julia -> latest LTS
#   - latest stable
#   - some older stable/lts versions (if needed)

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

julialts="julia-1.6.5-lts" # /opt/julia-1.6.5-lts
#juliastablev171="julia-1.7.1-stable" # /opt/julia-1.7.1-stable
juliastablev172="julia-1.7.2-stable" # /opt/julia-1.7.2-stable # current stable
# /opt/julia -> symlink to selected version (current)
# juliastablev160="julia-1.6.0-stable" # add more in APPS/opt/ if needed

# link all versions in /usr/bin/
$ROOTCMD ln -s $juliapath/$julialts/bin/julia /usr/bin/julia-1.6.5
$ROOTCMD ln -s $juliapath/$juliastablev172/bin/julia /usr/bin/julia-1.7.2
$ROOTCMD ln -s $juliapath/julia/bin/julia /usr/bin/julia
# $ROOTCMD ln -s /$juliapath/$juliastablev160/bin/julia /usr/bin/julia-1.6.0 # add more if needed

# create directory and export path
$ROOTCMD mkdir -p $JULIA_DEPOT_PATH
ainsl    /etc/bash.bashrc "export JULIA_DEPOT_PATH=/usr/share/julia/"

# export path to user specific REPL-history file (otherwise get's shared with all users)
ainsl    /etc/bash.bashrc 'export JULIA_HISTORY=$HOME/.julia/logs/repl_history.jl'

# install minimal packages (IJulia)
$ROOTCMD julia $juliapath/julia_init.jl --install-min
$ROOTCMD julia-1.6.5 $juliapath/julia_init.jl --install-min
#$ROOTCMD julia-1.7.2 $juliapath/julia_init.jl --install-min # current

# copy IJulia Kernel to $jupyter_kernels
$ROOTCMD chown -R root:smail $JULIA_DEPOT_PATH
#$ROOTCMD chmod -R g+rw $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH/registries/General
#$ROOTCMD mv -i .local/share/jupyter/kernels/julia-* $jupyter_kernels/
$ROOTCMD cp -a .local/share/jupyter/kernels/julia-1.6 /usr/share/jupyter/kernels/
$ROOTCMD cp -a .local/share/jupyter/kernels/julia-1.7 /usr/share/jupyter/kernels/

# add cronjob for 
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia"
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia/registries/General"


exit $error