#!/bin/bash

# Configures Julia (withouth packages)
# Packages are loaded in the JULIA class
# Julia must be already distributed into $files/JULIA/opt 
# Suggested versions to install (min):
#   - /opt/julia -> latest LTS
#   - latest stable
#   - some older stable/lts versions (if needed)

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# array of julia versions: juliaVersArr
# main versions (will be suffixed with -stable and -lts): juliaVersStable, juliaVersLTS
# load the list of versions (and juliaVersStable and juliaVersLTS) from the config file
source $FAI/files/archives/APPS/opt/get-julia-versions.conf

# link all versions in /usr/bin/
for vers in "${!juliaVersArr[@]}"; do
    if [ "$vers" = "$juliaVersStable" ]; then
        # link stable version
        $ROOTCMD ln -s $juliapath/$vers-stable/bin/julia /usr/bin/$vers
    elif [ "$vers" = "$juliaVersLTS" ]; then
        # link lts version
        $ROOTCMD ln -s $juliapath/$vers-lts/bin/julia /usr/bin/$vers
    else
        # other versions don't have a suffix
        $ROOTCMD ln -s $juliapath/$vers/bin/julia /usr/bin/$vers
    fi
done
# link default (stable) version in /usr/bin
$ROOTCMD ln -s $juliapath/julia/bin/julia /usr/bin/julia

# create directory and export path
$ROOTCMD mkdir -p $JULIA_DEPOT_PATH
ainsl    /etc/bash.bashrc "export JULIA_DEPOT_PATH=/usr/share/julia/"

# export path to user specific REPL-history file (otherwise get's shared with all users)
ainsl    /etc/bash.bashrc 'export JULIA_HISTORY=$HOME/.julia/logs/repl_history.jl'

# install minimal packages (IJulia)
# first the default (stable) version
$ROOTCMD julia $juliapath/julia_init.jl --install-min
# then the lts version
$ROOTCMD $juliaVersLTS $juliapath/julia_init.jl --install-min
# other versions
for vers in "${!juliaVersArr[@]}"; do
    if [ "$vers" = "$juliaVersStable" ]; then
        # already done but may be needed at some point at time
        echo " " # if should not be empty
    elif [ "$vers" = "$juliaVersLTS" ]; then
        # already done but may be needed at some point at time
        echo " " # if should not be empty
    else
        # other versions
        $ROOTCMD $vers $juliapath/julia_init.jl --install-min
    fi
done

# modify permissions
$ROOTCMD chown -R root:smail $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH
$ROOTCMD chmod -R ugo+rwx $JULIA_DEPOT_PATH/registries/General

# copy IJulia Kernels to $jupyter_kernels
for vers in "${!juliaVersArr[@]}"; do
    shortvers=${vers%.*}
    $ROOTCMD cp -a .local/share/jupyter/kernels/$shortvers /usr/share/jupyter/kernels/
done

# add cronjob to fix permissions of the packages
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia"
ainsl -Q /etc/crontab "* * * * *    root    chmod -R ugo+rwx /usr/share/julia/registries/General"


exit $error
