#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
[ "$flag_menu" ] && exit 0

# define host-independent classes
echo "GRUB_PC FAIBASE"

# define host-specific classes
case $HOSTNAME in
    cip*)
        echo "BASE-FOCAL AFS CIP APPS JULIA-PKGS";;
        # AFS CIP APPS JULIA-PKGS";;
#   # Webserver (optional)
    juno)
        echo "BASE-FOCAL WEBSERVER";;
#   # Backup Ubuntu 18:
    *)
        echo "BASE-BIONIC AFS CIP APPS JULIA-PKGS";;
#   # Faster, no julia packages
#   *)
#       echo "BASE-BIONIC AFS CIP APPS";;
#   # Minimal working system
#   *)
#       echo "BASE-BIONIC AFS CIP";;
esac

# DEMO
# case $HOSTNAME in
#    faiserver)
#        echo "FAIBASE DEBIAN DEMO FAISERVER" ;;
#    demohost|client*)
#        echo "FAIBASE DEBIAN DEMO" ;;
#    xfcehost)
#        echo "FAIBASE DEBIAN DEMO XORG XFCE LVM";;
#    gnomehost)
#        echo "FAIBASE DEBIAN DEMO XORG GNOME";;
#    centos)
#        echo "FAIBASE CENTOS"   # you may want to add class XORG here
#        ifclass I386 && echo CENTOS6_32  # AFAIK there's no 32bit C7
#        ifclass AMD64 && echo CENTOS7_64
#        exit 0 ;; # CentOS does not use the GRUB class
#    slchost)
#        # Scientific Linux Cern, is very similar to CentOS. SLC should alsways use the class CENTOS
#        echo "FAIBASE CENTOS SLC"  # you may want to add class XORG here
#        ifclass I386 && echo SLC7_32
#        ifclass AMD64 && echo SLC7_64
#        exit 0 ;; # CentOS/SLC does not use the GRUB class
#    *)
#        echo "FAIBASE DEBIAN DEMO" ;;
#esac
