#! /bin/bash
# support for GRUB version 2

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Add support for newest Intel GPU driver
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="noquiet nosplash"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/g' $target/etc/default/grub

$ROOTCMD update-grub

exit $error
