#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

#####################################################################
# Prepare and initialize cluster (SLURM)

# add compphys to group slurm
$ROOTCMD addgroup compphys slurm

# create folders and change permissions
$ROOTCMD mkdir /var/spool/slurm
$ROOTCMD chown compphys:root /var/spool/slurm
$ROOTCMD chown munge:munge /etc/munge/munge.key
$ROOTCMD ldconfig -n /usr/lib/x86_64-linux-gnu/
# $ROOTCMD chown compphys:root /var/log/slurmctld.log # only on master
$ROOTCMD chown compphys:root /var/log/slurmd.log # nodes

$ROOTCMD chown

# enable slurmd
$ROOTCMD systemctl enable slurmd.service




exit $error
