#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# Install OpenMPI from compiled tarball (in $fai/files/ from neptun:/home/shk/...)

file="openmpi"
filename="${file}_compiled.tar"

# Installationsdatei auf den Klienten uebertragen
cp $FAI/files/$filename $target/tmp/

# extract
$ROOTCMD tar -xf /tmp/$filename -C /tmp
# copy to /usr/local/
# $ROOTCMD cp -r /tmp/$file/* /usr/local/ # why isn't this working??? Need:
# cp -r $target/tmp/$file/* $target/usr/local/ # need to use the right bash:
$ROOTCMD bash -c "cp -r /tmp/$file/* /usr/local/"

# copy also to /home/shk/pmix (compile path on neptun), as this path is fixed compiled in some binaries
$ROOTCMD bash -c "cp -r /tmp/$file /home/shk/$file"

exit $error
