#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set correct timezone for local time

tz='Europe/Berlin'

$ROOTCMD rm /etc/localtime
$ROOTCMD ln -s /usr/share/zoneinfo/$tz /etc/localtime
$ROOTCMD echo $tz | tee /etc/timezone

exit $error
